// Code generated by github.com/swaggest/swac v0.1.35, DO NOT EDIT.

package faces

// Output structure is generated from "#/components/schemas/Output".
type Output struct {
	ElapsedSec float64      `json:"elapsedSec,omitempty"`
	Faces      []GoFaceFace `json:"faces,omitempty"`
	Found      int64        `json:"found,omitempty"`
}

// GoFaceFace structure is generated from "#/components/schemas/GoFaceFace".
type GoFaceFace struct {
	Descriptor *[]float64      `json:"Descriptor,omitempty"`
	Rectangle  *ImageRectangle `json:"Rectangle,omitempty"`
	Shapes     *[]ImagePoint   `json:"Shapes,omitempty"`
}

// ImageRectangle structure is generated from "#/components/schemas/ImageRectangle".
type ImageRectangle struct {
	Max *ImagePoint `json:"Max,omitempty"`
	Min *ImagePoint `json:"Min,omitempty"`
}

// ImagePoint structure is generated from "#/components/schemas/ImagePoint".
type ImagePoint struct {
	X int64 `json:"X,omitempty"`
	Y int64 `json:"Y,omitempty"`
}
