// Code generated by github.com/swaggest/swac v0.1.35, DO NOT EDIT.

package faces

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
)

// UploadImageRequest is operation request value.
type UploadImageRequest struct {
	Image UploadFile // Image is an optional `image` parameter in formData.
	pipeUpload
}

// encode creates *http.Request for request data.
func (request *UploadImageRequest) encode(ctx context.Context, baseURL string) (*http.Request, error) {
	requestURI := baseURL + "/image"

	request.initPipe()
	go func() {
		defer request.close()

		request.addFile(request.Image, "image")
	}()

	req, err := http.NewRequest(http.MethodPost, requestURI, request.pipeReader)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", request.multipartWriter.FormDataContentType())
	req.Header.Set("Accept", "application/json")

	req = req.WithContext(ctx)

	return req, err
}

// UploadImageResponse is operation response value.
type UploadImageResponse struct {
	StatusCode int
	RawBody    []byte  // RawBody contains read bytes of response body.
	ValueOK    *Output // ValueOK is a value of 200 OK response.
}

// decode loads data from *http.Response.
func (result *UploadImageResponse) decode(resp *http.Response) error {
	var err error

	dump := bytes.NewBuffer(nil)
	body := io.TeeReader(resp.Body, dump)

	result.StatusCode = resp.StatusCode

	switch resp.StatusCode {
	case http.StatusOK:
		err = json.NewDecoder(body).Decode(&result.ValueOK)
		if err != nil {
			err = fmt.Errorf("failed to decode 'post /image' OK response: %w", err)
		}
	default:
		_, readErr := ioutil.ReadAll(body)
		if readErr != nil {
			err = errors.New("unexpected response status: " + resp.Status +
				", could not read response body: " + readErr.Error())
		} else {
			err = errors.New("unexpected response status: " + resp.Status)
		}
	}

	result.RawBody = dump.Bytes()

	if err != nil {
		return responseError{
			resp: resp,
			body: dump.Bytes(),
			err:  err,
		}
	}

	return nil
}

// UploadImage performs REST operation.
func (c *Client) UploadImage(ctx context.Context, request UploadImageRequest) (result UploadImageResponse, err error) {
	if c.InstrumentCtxFunc != nil {
		ctx = c.InstrumentCtxFunc(ctx, http.MethodPost, "/image", &request)
	}

	if c.Timeout != 0 {
		var cancel func()
		ctx, cancel = context.WithTimeout(ctx, c.Timeout)

		defer cancel()
	}

	req, err := request.encode(ctx, c.BaseURL)
	if err != nil {
		return result, err
	}

	resp, err := c.transport.RoundTrip(req)
	if err != nil {
		request.Cancel(err)

		return result, err
	}

	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	err = result.decode(resp)

	return result, err
}
